name: logistix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  blur: ^4.0.2
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  go_router: ^15.2.0
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  mapbox_maps_flutter: ^2.8.0
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - assets/images/