name: logistix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: 

  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  dio_cache_interceptor: ^4.0.3
  equatable: ^2.0.7
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  go_router: ^15.2.0
  google_maps_flutter: ^2.12.3
  flutter_chat_core: ^2.6.1
  flutter_chat_ui: ^2.5.2
  flyer_chat_system_message:
  flyer_chat_text_message:
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  flutter_multi_formatter: 
  # intl: ^0.20.2
  overlay_support: ^2.1.0
  permission_handler: ^12.0.0+1
  
  rounded_loading_button: ^2.1.0
  # rounded_loading_button:
  #   git:
  #     url: https://github.com/Enri-code/rounded_loading_button-2.1.1.git
  #     ref: 2.1.1

  smooth_page_indicator: ^1.2.1
  uuid: ^4.5.1

  # app_badge_plus: ^1.2.3
  # badges: ^3.1.2

  # awesome_notifications: ^0.10.1
  # awesome_notifications_fcm: ^0.10.1
  # ios_communication_notification: ^1.0.4

  # sound_library: ^1.0.0
  leak_tracker:
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator:

  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - assets/images/
    - assets/json/